#+TITLE: conception
#+AUTHOR: daotoyi
#+DATE: \today
#+EMAIL: daotoyi@foxmail.com
#+LaTeX_CLASS: article-prefer
#+OPTIONS: H:4 num:t toc:t
#+OPTIONS: creator:t @:t ^:t |:t f:t todo:t <:t *:t Tex:t email:t
#+PROPERTY: CLOCK_INTO_DRAWER t
\newpage

* basic
** OMO (Open market operations) 公开市场操作

公开市场操作是中央银行吞吐基础货币，调节市场流动性的主要货币政策工具，通过中央银行与市场交易对手进行有价证券和外汇交易，实现货币政策调控目标。

中国公开市场操作包括人民币操作和外汇操作两部分。

从交易品种看，中国人民银行公开市场业务债券交易主要包括回购交易、现券交易和发行中央银行票据。

*** 回购交易

- 正回购
  为中国人民银行向一级交易商卖出有价证券，并约定在未来购回的行为。央行进行正回购操作为回收流动性，正回购到期则为投放流动性。

- 逆回购
  为中国人民银行向一级交易商购买有价证券，并约定在未来由一级交易商购回的行为。央行进行逆回购操作为投放流动性，逆回购到期则为回收流动性。

*** 现券交易
- 现券买断
  央行直接从二级市场买入债券，一次性地投放基础货币；

- 现券卖断
  为央行直接卖出持有债券，一次性地回笼基础货币。

*** 中央银行票据

即中国人民银行发行的短期债券，央行通过发行央行票据可以回笼基础货币，央行票据到期则体现为投放基础货币。

**** note

OMO、MLF 和 LPR 是央行针对不同期限和不同目标的利率调整工具。

理论上来看，OMO、MLF 以及 LPR 三者变化实现不同的政策效果，并且调整利率曲线变化，因而三者不一定需要同时变化.

** MLF（Medium-term Lending Facility）中期借贷便利

*** feature
- 央行借钱给商业银行(有门槛的，就是质押品)
- 操作时段一般为 3 个月、6个月、1年。
  
*** function
- 为了增加市场流动性
** LPR (Loan Prime Rate) 贷款市场报价利率
LPR 浮动利率是由 LPR 市场报价利率加基点构成的，基点数是固定的.

*** 常识
- **贷款市场报价利率** ，也叫 **贷款基础利率** ，由 18 家银行共同报价计算得来的，央行用它来代替原有的贷款基准利率。
- 利率分为 1 年期和 5 年期以上，房贷是和 5 年期以上的利率挂钩的。是在 5 年期的 LPR 基础上加基点上浮而来的。
- LPR 每个月 20 日（遇节假日顺延）会更新一次
- 房贷不会跟随 LPR 每月更新。
** SLF 常备借贷便利
主要功能是满足金融机构期限较长的大额流动性需求，在银行体系流动性出现临时性波动时相机运用。

- 面对的是政策性银行和全国性商业银行
- 期限为 1-3 个月
- 利率水平则根据货币政策调控、引导市场利率的需要等因素综合确定。
  
** SLO 短期流动性调节工具。
- 每周二、周四，央行一般都会进行公开市场操作，目前最主要的是回购操作。
- 主要以期限在 7 天以内的正回购和逆回购为主
- 央行可以通过 SLO 来调节 7 天以内的超短期货币供应和利率，遇节假日可适当延长操作期限
- 采用市场化利率招标方式开展操作。

** PSL 全称为抵押补充贷款工具

- 多是央行为了支持一些特定项目的建设向政策性银行(如国开行)提供的成本较低的抵押贷款，期限一般在 3-5 年;
- 它还可以用于向市场投放货币，调节中期市场利率。

** 基点
bp 是指基点 Basis Point（bp）

基点的定义是“百分之零点零一”（0.01%）

金融方面，债券和票据利率改变量的度量单位。一个基点等于 0.01 个百分点，即 0.01%，因此，100 个基点等于 1%。

** 逆回购
逆回购从本质上讲是一种短期贷款，就是你把钱借给别人，获得固定利息；别人用债券（国债或企业债）作抵押，到期还本付息。

上海市场国债逆回购：交易数量为 10 万或 10 万的整数倍；

深圳市场债券逆回购：交易数量为 1000 元或其整数倍；

https://pic4.zhimg.com/80/v2-1bb4dea5ae4f6ff7d1b9a1b405e09467_1440w.jpg

*** 净收益
净收益 = 成交金额×年收益率×资金实际占用天数/365 天 - 手续费

比活期存款利息高.

** 一致行动人
界定为根据正式或非正式的协议或默契，积极合作，通过其中任何人取得目标公司股权以获得或巩固对目标公司控制权的人。

一致行动人协议一般都有一定的期限，在期限届满后，协议失效。也可能因为目的完成而被解除或撤销。一般保持一致行动人往往是为了某种特殊目的，例如上市。

** 实际控制人
是指虽不是公司的股东，但通过投资关系、协议或者其他安排，能够实际支配公司的人。

* fund
基金的组织形式通常是采取 **有限合似制** ，而非公司制。这是因为有限合伙只涉及一次征税，即退出 的时候交税。

如果是有限责任公司，就涉及两层税制，公司层面交一次企业所得税，分红的时候 人交一次个人所得税。
* invest
** 投资关系
https://pic3.zhimg.com/80/v2-b80214179bddb463ae80d26897a91668_1440w.jpg?source=1940ef5c

一级市场（未上市前的公司）私募股权投资可以根据所投资标的成长阶段分为几个种类，
1. 第一步是 天使基金(种子、天使、PreA 轮)，
2. 第二是 VC 基金(A-C 轮)，第三是 PE 基金（（轮后到上 市）。

*** LP（Limited Partner）有限合伙人
出资人

在美国，绝大多数情况下，LP 都有一个最低投资额度——这个数字一般是 600 万美金，中国的话大多都是 600 万人民币。

为了避免一个 LP 注资过多，大多数公司也会有一个最高投资额度——常见的则是由 1000 万至 2000 万不等。

一般 LP 的资金都会有一个锁定周期（Lock-Up Period），一般为一年至数年不等（要看公司具体投资的项目而定）。

在合伙企业不能清偿到期债务时，LP 仅以其对有限合伙企业的出资为限承担责任，剩余的由 GP 承担无限连带责任。

一般 GP 投 1%， LP 投 99%
*** GP (General Partner) 普通合伙人
大 GP 的收入一般是所谓 2/20，就是 2%的管理费+20%的收益分成（Carry）.

GP 就是负责募、投、管、退，这四个主要职责，对基金的收益负责。

普通合伙人是指在合伙企业中对合伙企业的债务依法承担无限连带责任的自然人、法人和其他组织。

GP 需要对合伙企业债务承担无限连带责任，为了尽可能规避经营风险，实践中一般选择有限责任公司作为 GP 主体。

*** Angels（Angel Investment）天使投资
天使投资选择的企业都会是一些非常非常早期的企业，他们甚至没有一个完整的产品，或者仅仅只有一个概念。

*** VC（Venture Capital）风险投资

*** PE（Private Equity）私募基金

*** IB（Investment Banking）投资银行

*** FOF（Fund of Fund, FoF）母基金
FoF 一般是不会股票，债券，期货进行投资的。他们会选择投资那些本身盈利能力很强的基金公司

\newpage





